export const PANEL_STYLE = {
  wrapper: {
    position: 'fixed',
    left: '50%',
    bottom: '24px',
    transform: 'translateX(-50%)',
    width: 'min(92vw, 760px)',
    zIndex: 30,
    touchAction: 'auto',
  },
  panel: {
    background: 'rgba(10, 12, 14, 0.75)',
    border: '1px solid rgba(255, 215, 160, 0.25)',
    borderRadius: '18px',
    padding: '16px',
    boxShadow: '0 16px 40px rgba(0, 0, 0, 0.45)',
    backdropFilter: 'blur(8px)',
  },
  title: {
    fontFamily: 'KaiTi, STKaiti, serif',
    color: '#f2e6c9',
    letterSpacing: '0.12em',
    fontSize: '12px',
    marginBottom: '10px',
  },
  chips: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    marginBottom: '12px',
  },
  chip: {
    fontFamily: 'KaiTi, STKaiti, serif',
    background: 'rgba(255, 215, 160, 0.12)',
    color: '#f7e7b3',
    padding: '4px 10px',
    borderRadius: '999px',
    fontSize: '12px',
    border: '1px solid rgba(255, 215, 160, 0.25)',
  },
  input: {
    width: '100%',
    background: 'rgba(255, 255, 255, 0.06)',
    border: '1px solid rgba(255, 215, 160, 0.2)',
    borderRadius: '12px',
    padding: '10px 12px',
    color: '#f8f1de',
    fontFamily: 'KaiTi, STKaiti, serif',
    fontSize: '14px',
    outline: 'none',
    resize: 'none',
    minHeight: '72px',
  },
  actions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
    marginTop: '10px',
  },
  button: {
    background: 'linear-gradient(120deg, #f5d68a, #f2b96d)',
    color: '#1a1206',
    borderRadius: '10px',
    padding: '8px 18px',
    fontSize: '14px',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
  },
  secondaryButton: {
    background: 'transparent',
    color: '#f2e6c9',
    borderRadius: '10px',
    padding: '8px 16px',
    fontSize: '14px',
    border: '1px solid rgba(255, 215, 160, 0.35)',
    cursor: 'pointer',
  },
  answer: {
    marginTop: '12px',
    color: '#f8f1de',
    fontSize: '14px',
    lineHeight: 1.7,
    fontFamily: 'KaiTi, STKaiti, serif',
  },
  answerHeader: {
    marginTop: '10px',
    marginBottom: '8px',
  },
  answerStep: {
    fontSize: '11px',
    color: '#d9caa5',
    letterSpacing: '0.18em',
  },
  answerTitle: {
    fontSize: '15px',
    color: '#f7e7b3',
    marginTop: '4px',
  },
  answerHint: {
    fontSize: '12px',
    color: '#cbb78e',
    marginTop: '4px',
  },
  answerCard: {
    marginTop: '10px',
    padding: '12px',
    borderRadius: '14px',
    border: '1px solid rgba(255, 215, 160, 0.2)',
    background: 'rgba(7, 8, 12, 0.55)',
    overflowY: 'auto',
    touchAction: 'pan-y',
    WebkitOverflowScrolling: 'touch',
  },
  pager: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '10px',
    gap: '8px',
  },
  pagerButton: {
    background: 'rgba(255, 215, 160, 0.12)',
    color: '#f2e6c9',
    borderRadius: '10px',
    padding: '6px 12px',
    fontSize: '12px',
    border: '1px solid rgba(255, 215, 160, 0.25)',
    cursor: 'pointer',
  },
  pagerIndicator: {
    color: '#d9caa5',
    fontSize: '12px',
    letterSpacing: '0.12em',
  },
  captionWrapper: {
    position: 'fixed',
    left: '50%',
    bottom: '7vh',
    transform: 'translateX(-50%)',
    width: 'min(94vw, 880px)',
    zIndex: 40,
    pointerEvents: 'auto',
  },
  captionPanel: {
    background: 'rgba(8, 10, 14, 0.7)',
    border: '1px solid rgba(255, 215, 160, 0.18)',
    borderRadius: '18px',
    padding: '14px 16px',
    boxShadow: '0 18px 45px rgba(0, 0, 0, 0.45)',
    backdropFilter: 'blur(10px)',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  captionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  captionTitle: {
    fontFamily: 'KaiTi, STKaiti, serif',
    color: '#f7e7b3',
    fontSize: '14px',
    letterSpacing: '0.08em',
  },
  captionStep: {
    fontSize: '11px',
    color: '#d9caa5',
    letterSpacing: '0.2em',
  },
  captionBody: {
    color: '#f8f1de',
    fontSize: '14px',
    lineHeight: 1.7,
    maxHeight: '28vh',
    overflowY: 'auto',
    paddingRight: '4px',
    touchAction: 'pan-y',
    WebkitOverflowScrolling: 'touch',
  },
  captionFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '10px',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(5, 6, 10, 0.6)',
    backdropFilter: 'blur(6px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 60,
    padding: '20px',
  },
  modalCard: {
    width: 'min(88vw, 420px)',
    background: 'rgba(12, 14, 18, 0.92)',
    border: '1px solid rgba(255, 215, 160, 0.3)',
    borderRadius: '16px',
    padding: '16px',
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.55)',
  },
  modalTitle: {
    fontSize: '15px',
    color: '#f7e7b3',
    marginBottom: '6px',
    letterSpacing: '0.08em',
  },
  modalSubtitle: {
    fontSize: '12px',
    color: '#cbb78e',
    marginBottom: '10px',
  },
  modalStars: {
    display: 'flex',
    gap: '8px',
    marginBottom: '12px',
  },
  starButton: {
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontSize: '22px',
    padding: 0,
    lineHeight: 1,
  },
  starOn: {
    color: '#f5d68a',
    textShadow: '0 0 10px rgba(245, 214, 138, 0.5)',
  },
  starOff: {
    color: 'rgba(245, 214, 138, 0.35)',
  },
  modalInput: {
    width: '100%',
    minHeight: '90px',
    borderRadius: '12px',
    border: '1px solid rgba(255, 215, 160, 0.2)',
    background: 'rgba(255, 255, 255, 0.05)',
    padding: '10px 12px',
    color: '#f8f1de',
    fontFamily: 'KaiTi, STKaiti, serif',
    fontSize: '14px',
    outline: 'none',
    resize: 'none',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: '12px',
  },
  modalSubmit: {
    background: 'linear-gradient(120deg, #f5d68a, #f2b96d)',
    color: '#1a1206',
    borderRadius: '10px',
    padding: '8px 16px',
    fontSize: '13px',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
  },
  modalThanks: {
    marginTop: '10px',
    color: '#f8f1de',
    fontSize: '13px',
  },
  error: {
    marginTop: '8px',
    color: '#fca5a5',
    fontSize: '13px',
  },
}

export const MARKDOWN_STYLE = {
  h1: { fontSize: '18px', margin: '8px 0', color: '#f7e7b3' },
  h2: { fontSize: '16px', margin: '8px 0', color: '#f7e7b3' },
  h3: { fontSize: '15px', margin: '8px 0', color: '#f7e7b3' },
  p: { margin: '6px 0' },
  ul: { paddingLeft: '18px', margin: '6px 0' },
  ol: { paddingLeft: '18px', margin: '6px 0' },
  li: { marginBottom: '4px' },
  blockquote: {
    margin: '8px 0',
    paddingLeft: '10px',
    borderLeft: '2px solid rgba(255, 215, 160, 0.4)',
    color: '#f8f1de',
  },
  code: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
    background: 'rgba(255, 255, 255, 0.1)',
    padding: '2px 6px',
    borderRadius: '6px',
    fontSize: '12px',
  },
  pre: {
    margin: '8px 0',
    padding: '10px',
    borderRadius: '10px',
    background: 'rgba(0, 0, 0, 0.35)',
    overflowX: 'auto',
  },
}

export const markdownComponents = {
  h1: ({ node, ...props }) => <h1 style={MARKDOWN_STYLE.h1} {...props} />,
  h2: ({ node, ...props }) => <h2 style={MARKDOWN_STYLE.h2} {...props} />,
  h3: ({ node, ...props }) => <h3 style={MARKDOWN_STYLE.h3} {...props} />,
  p: ({ node, ...props }) => <p style={MARKDOWN_STYLE.p} {...props} />,
  ul: ({ node, ...props }) => <ul style={MARKDOWN_STYLE.ul} {...props} />,
  ol: ({ node, ...props }) => <ol style={MARKDOWN_STYLE.ol} {...props} />,
  li: ({ node, ...props }) => <li style={MARKDOWN_STYLE.li} {...props} />,
  blockquote: ({ node, ...props }) => <blockquote style={MARKDOWN_STYLE.blockquote} {...props} />,
  code: ({ inline, ...props }) =>
    inline ? <code style={MARKDOWN_STYLE.code} {...props} /> : <code style={MARKDOWN_STYLE.code} {...props} />,
  pre: ({ node, ...props }) => <pre style={MARKDOWN_STYLE.pre} {...props} />,
}
