export const TAROT_DATA = [
  { id: 0, name: "The Fool", nameCN: "愚人", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Fool.webp" },
  { id: 1, name: "The Magician", nameCN: "魔术师", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Magician.webp" },
  { id: 2, name: "The High Priestess", nameCN: "女祭司", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_High_Priestess.webp" },
  { id: 3, name: "The Empress", nameCN: "皇后", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Empress.webp" },
  { id: 4, name: "The Emperor", nameCN: "皇帝", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Emperor.webp" },
  { id: 5, name: "The Hierophant", nameCN: "教皇", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Hierophant.webp" },
  { id: 6, name: "The Lovers", nameCN: "恋人", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Lovers.webp" },
  { id: 7, name: "The Chariot", nameCN: "战车", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Chariot.webp" },
  { id: 8, name: "Strength", nameCN: "力量", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Strength.webp" },
  { id: 9, name: "The Hermit", nameCN: "隐者", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Hermit.webp" },
  { id: 10, name: "Wheel of Fortune", nameCN: "命运之轮", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Wheel_of_Fortune.webp" },
  { id: 11, name: "Justice", nameCN: "正义", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Justice.webp" },
  { id: 12, name: "The Hanged Man", nameCN: "倒吊人", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Hanged_Man.webp" },
  { id: 13, name: "Death", nameCN: "死神", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Death.webp" },
  { id: 14, name: "Temperance", nameCN: "节制", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Temperance.webp" },
  { id: 15, name: "The Devil", nameCN: "恶魔", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Devil.webp" },
  { id: 16, name: "The Tower", nameCN: "高塔", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Tower.webp" },
  { id: 17, name: "The Star", nameCN: "星星", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Star.webp" },
  { id: 18, name: "The Moon", nameCN: "月亮", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Moon.webp" },
  { id: 19, name: "The Sun", nameCN: "太阳", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_Sun.webp" },
  { id: 20, name: "Judgement", nameCN: "审判", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Judgement.webp" },
  { id: 21, name: "The World", nameCN: "世界", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/The_World.webp" },
  { id: 22, name: "Ace of Wands", nameCN: "权杖王牌", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Ace_of_Wands.webp" },
  { id: 23, name: "Two of Wands", nameCN: "权杖二", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Two_of_Wands.webp" },
  { id: 24, name: "Three of Wands", nameCN: "权杖三", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Three_of_Wands.webp" },
  { id: 25, name: "Four of Wands", nameCN: "权杖四", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Four_of_Wands.webp" },
  { id: 26, name: "Five of Wands", nameCN: "权杖五", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Five_of_Wands.webp" },
  { id: 27, name: "Six of Wands", nameCN: "权杖六", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Six_of_Wands.webp" },
  { id: 28, name: "Seven of Wands", nameCN: "权杖七", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Seven_of_Wands.webp" },
  { id: 29, name: "Eight of Wands", nameCN: "权杖八", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Eight_of_Wands.webp" },
  { id: 30, name: "Nine of Wands", nameCN: "权杖九", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Nine_of_Wands.webp" },
  { id: 31, name: "Ten of Wands", nameCN: "权杖十", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Ten_of_Wands.webp" },
  { id: 32, name: "Page of Wands", nameCN: "权杖侍从", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Page_of_Wands.webp" },
  { id: 33, name: "Knight of Wands", nameCN: "权杖骑士", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Knight_of_Wands.webp" },
  { id: 34, name: "Queen of Wands", nameCN: "权杖王后", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Queen_of_Wands.webp" },
  { id: 35, name: "King of Wands", nameCN: "权杖国王", element: "Fire", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/King_of_Wands.webp" },
  { id: 36, name: "Ace of Cups", nameCN: "圣杯王牌", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Ace_of_Cups.webp" },
  { id: 37, name: "Two of Cups", nameCN: "圣杯二", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Two_of_Cups.webp" },
  { id: 38, name: "Three of Cups", nameCN: "圣杯三", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Three_of_Cups.webp" },
  { id: 39, name: "Four of Cups", nameCN: "圣杯四", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Four_of_Cups.webp" },
  { id: 40, name: "Five of Cups", nameCN: "圣杯五", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Five_of_Cups.webp" },
  { id: 41, name: "Six of Cups", nameCN: "圣杯六", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Six_of_Cups.webp" },
  { id: 42, name: "Seven of Cups", nameCN: "圣杯七", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Seven_of_Cups.webp" },
  { id: 43, name: "Eight of Cups", nameCN: "圣杯八", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Eight_of_Cups.webp" },
  { id: 44, name: "Nine of Cups", nameCN: "圣杯九", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Nine_of_Cups.webp" },
  { id: 45, name: "Ten of Cups", nameCN: "圣杯十", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Ten_of_Cups.webp" },
  { id: 46, name: "Page of Cups", nameCN: "圣杯侍从", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Page_of_Cups.webp" },
  { id: 47, name: "Knight of Cups", nameCN: "圣杯骑士", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Knight_of_Cups.webp" },
  { id: 48, name: "Queen of Cups", nameCN: "圣杯王后", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Queen_of_Cups.webp" },
  { id: 49, name: "King of Cups", nameCN: "圣杯国王", element: "Water", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/King_of_Cups.webp" },
  { id: 50, name: "Ace of Swords", nameCN: "宝剑王牌", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Ace_of_Swords.webp" },
  { id: 51, name: "Two of Swords", nameCN: "宝剑二", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Two_of_Swords.webp" },
  { id: 52, name: "Three of Swords", nameCN: "宝剑三", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Three_of_Swords.webp" },
  { id: 53, name: "Four of Swords", nameCN: "宝剑四", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Four_of_Swords.webp" },
  { id: 54, name: "Five of Swords", nameCN: "宝剑五", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Five_of_Swords.webp" },
  { id: 55, name: "Six of Swords", nameCN: "宝剑六", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Six_of_Swords.webp" },
  { id: 56, name: "Seven of Swords", nameCN: "宝剑七", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Seven_of_Swords.webp" },
  { id: 57, name: "Eight of Swords", nameCN: "宝剑八", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Eight_of_Swords.webp" },
  { id: 58, name: "Nine of Swords", nameCN: "宝剑九", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Nine_of_Swords.webp" },
  { id: 59, name: "Ten of Swords", nameCN: "宝剑十", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Ten_of_Swords.webp" },
  { id: 60, name: "Page of Swords", nameCN: "宝剑侍从", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Page_of_Swords.webp" },
  { id: 61, name: "Knight of Swords", nameCN: "宝剑骑士", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Knight_of_Swords.webp" },
  { id: 62, name: "Queen of Swords", nameCN: "宝剑王后", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Queen_of_Swords.webp" },
  { id: 63, name: "King of Swords", nameCN: "宝剑国王", element: "Air", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/King_of_Swords.webp" },
  { id: 64, name: "Ace of Pentacles", nameCN: "星币王牌", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Ace_of_Pentacles.webp" },
  { id: 65, name: "Two of Pentacles", nameCN: "星币二", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Two_of_Pentacles.webp" },
  { id: 66, name: "Three of Pentacles", nameCN: "星币三", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Three_of_Pentacles.webp" },
  { id: 67, name: "Four of Pentacles", nameCN: "星币四", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Four_of_Pentacles.webp" },
  { id: 68, name: "Five of Pentacles", nameCN: "星币五", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Five_of_Pentacles.webp" },
  { id: 69, name: "Six of Pentacles", nameCN: "星币六", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Six_of_Pentacles.webp" },
  { id: 70, name: "Seven of Pentacles", nameCN: "星币七", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Seven_of_Pentacles.webp" },
  { id: 71, name: "Eight of Pentacles", nameCN: "星币八", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Eight_of_Pentacles.webp" },
  { id: 72, name: "Nine of Pentacles", nameCN: "星币九", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Nine_of_Pentacles.webp" },
  { id: 73, name: "Ten of Pentacles", nameCN: "星币十", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Ten_of_Pentacles.webp" },
  { id: 74, name: "Page of Pentacles", nameCN: "星币侍从", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Page_of_Pentacles.webp" },
  { id: 75, name: "Knight of Pentacles", nameCN: "星币骑士", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Knight_of_Pentacles.webp" },
  { id: 76, name: "Queen of Pentacles", nameCN: "星币王后", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/Queen_of_Pentacles.webp" },
  { id: 77, name: "King of Pentacles", nameCN: "星币国王", element: "Earth", image: "https://tarot-1378447783.cos.ap-guangzhou.myqcloud.com/web_pictrue/King_of_Pentacles.webp" }
]
